version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/staticfiles
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
      - ./staticfile:/static
    ports:
      - "8000:8000"
      - "8009:8009"
    env_file:
      - .env
