version: '3'
volumes:
  postgres_db_dev: {}
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/staticfiles
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
      - ./staticfile:/static
    ports:
      - "8000:8000"
      - "8009:8009"
    environment:
      - DB_HOST=db

  db:
    image: postgres
    # postgres_db_dev를 컨테이너 ~/data에 마운트
    volumes:
      - postgres_db_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234